name: Backend CI/CD

on:
  push:
    branches: [ main ]
    paths:
      - 'backend/**'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        
    - name: Create .env file
      run: |
        cd backend
        echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" > .env
        # 添加其他環境變數
        
    - name: Install Dependencies
      working-directory: ./backend
      run: |
        pip install -r requirements.txt
        pip install pytest
        
    - name: Run Tests
      working-directory: ./backend
      run: pytest || true